name: Publish
on:
  push:
    tags:
      - '**[0-9]+.[0-9]+.[0-9]+*'
jobs:
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Publish bin
        run: cargo publish --token ${CRATES_TOKEN} -p unity-reference-server
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
